# Generated by Django 5.2.7 on 2025-11-14 11:43

import apps.qa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_best', models.BooleanField(default=False, verbose_name='بهترین پاسخ')),
                ('is_true', models.BooleanField(default=False, verbose_name='پاسخ درست')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('photo', models.ImageField(blank=True, help_text='یک تصویر میتواند به رفع مشکلتان کمک میکند', null=True, upload_to=apps.qa.models.get_upload_path, verbose_name='تصویر کمکی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_pin', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verify', models.BooleanField(default=False, verbose_name='تائید')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر دادن')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها',
            },
        ),
    ]
