# Generated by Django 5.2.7 on 2025-11-14 11:43

import apps.news.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('verbose_name', models.CharField(max_length=110)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس ها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.news.models.thumbnail_upload_path, verbose_name='تصویر شاخص')),
                ('short_description', models.CharField(blank=True, max_length=110, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='نوشته شده در تاریخ')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='اخرین به روز رسانی')),
                ('is_active', models.BooleanField(verbose_name='فعال بودن')),
                ('is_pin', models.BooleanField(verbose_name='پین بودن')),
                ('is_verify', models.BooleanField(verbose_name='تایید شده')),
                ('meta_name', models.CharField(blank=True, null=True, verbose_name='نام سئو')),
                ('meta_description', models.CharField(blank=True, null=True, verbose_name='توضیح سئو')),
                ('meta_keywords', models.CharField(blank=True, help_text='بین کلمات باید (,) بگذارید', null=True, verbose_name='کلمات کلیدی')),
                ('article_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.course', verbose_name='درس مربوطه')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['is_pin', '-write_date', 'update_date', 'title', 'is_active', 'is_verify'],
            },
        ),
    ]
