# Generated by Django 5.2.7 on 2025-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشته شدن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_verify', models.BooleanField(default=False, verbose_name='مورد تائید')),
                ('is_pin', models.BooleanField(default=False, verbose_name='پین')),
                ('is_check_of_author_post', models.BooleanField(default=False, verbose_name='چک شده توسط نویسنده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
