# Generated by Django 5.2.7 on 2025-11-14 11:43

import apps.users.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام محور')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.users.models.main_point_upload_path, verbose_name='تصویر محور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محور')),
            ],
            options={
                'verbose_name': 'محور',
                'verbose_name_plural': 'محورها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path, verbose_name='عکس پروفایل')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='درباره من')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('confirmation_comments', models.BooleanField(default=False, help_text='اگر فعال باشد نظرات با تائید شما ارسال می شوند', verbose_name='تائیدی بودن نظرات')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('main_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mainpoint')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MiniMainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام زیر شاخه محور')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.users.models.main_point_upload_path, verbose_name='تصویر زیر شاخه محور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات زیر شاخه محور')),
                ('main_mainpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mainpoint')),
            ],
            options={
                'verbose_name': 'محور',
                'verbose_name_plural': 'محورها',
                'ordering': ['name'],
            },
        ),
    ]
