# Generated by Django 5.2.7 on 2025-11-08 15:15

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_confirmation_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام محور')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.users.models.main_point_upload_path, verbose_name='تصویر محور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محور')),
            ],
            options={
                'verbose_name': 'محور',
                'verbose_name_plural': 'محورها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mainpoint'),
        ),
    ]
