# Generated by Django 5.2.7 on 2025-11-14 11:59

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mainpoint_customuser_main_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniMainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='نام زیر شاخه محور')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.users.models.main_point_upload_path, verbose_name='تصویر زیر شاخه محور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات زیر شاخه محور')),
                ('main_mainpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mainpoint')),
            ],
            options={
                'verbose_name': 'محور',
                'verbose_name_plural': 'محورها',
                'ordering': ['name'],
            },
        ),
    ]
